services:
  app:
    image: node:22-bullseye
    working_dir: /app

    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - npm-cache:/root/.npm

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=8092

    ports:
      - "8092:8092"

    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 8092
      "

volumes:
  node_modules:
  npm-cache:
